# Generated by Django 5.0 on 2024-03-27 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationcollection',
            name='question',
        ),
    ]
