# Generated by Django 5.0 on 2024-03-27 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_remove_locationcollection_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapview',
            name='location_collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.locationcollection'),
        ),
    ]
