# Generated by Django 5.0 on 2024-06-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_polygonfeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationcollection',
            old_name='descripion',
            new_name='description',
        ),
    ]
