# Generated by Django 5.0 on 2024-06-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_rename_descripion_locationcollection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcollection',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
