# Generated by Django 5.0 on 2024-03-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_rename_location_linestringlocation_geometry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linestringlocation',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='pointlocation',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='polygonlocation',
            old_name='geometry',
            new_name='geom',
        ),
    ]
