# Generated by Django 5.0 on 2024-06-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_alter_locationcollection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_text',
            field=models.BooleanField(default=True, verbose_name='If the question must show the text field or not'),
        ),
    ]
