# Generated by Django 5.0 on 2024-03-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_rename_pointlocation_pointfeature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolygonLocation',
            new_name='PolygonFeature',
        ),
    ]
