# Generated by Django 5.0 on 2024-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_question_show_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation for the Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='show_text',
            field=models.BooleanField(default=True, verbose_name='Show the input text field'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
