# Generated by Django 5.0 on 2024-03-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_rename_polygonlocation_polygonfeature'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineStringLocation',
            new_name='LineFeature',
        ),
    ]
