# Generated by Django 5.0 on 2024-03-27 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_rename_linestringlocation_linefeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapview',
            name='geometries',
        ),
    ]
