# Generated by Django 5.0 on 2024-06-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0006_question_explanation_alter_question_show_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Explanation for the question'),
        ),
    ]
