# Generated by Django 5.0 on 2024-03-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_remove_location_answer_answer_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lines',
            field=models.ManyToManyField(blank=True, null=True, to='apiapp.linestringlocation'),
        ),
        migrations.AlterField(
            model_name='location',
            name='points',
            field=models.ManyToManyField(blank=True, null=True, to='apiapp.pointlocation'),
        ),
        migrations.AlterField(
            model_name='location',
            name='polygons',
            field=models.ManyToManyField(blank=True, null=True, to='apiapp.polygonlocation'),
        ),
    ]
