# Generated by Django 5.0 on 2024-03-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_remove_mapview_geometries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='locations',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='mapview',
            old_name='location_collection',
            new_name='location',
        ),
    ]
