# Generated by Django 5.0 on 2024-07-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0007_alter_question_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='show_text',
            new_name='has_text_input',
        ),
        migrations.RemoveField(
            model_name='linefeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pointfeature',
            name='description',
        ),
        migrations.RemoveField(
            model_name='polygonfeature',
            name='description',
        ),
        migrations.AddField(
            model_name='linefeature',
            name='annotation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='mapview',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Description of the MapView'),
        ),
        migrations.AddField(
            model_name='pointfeature',
            name='annotation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='polygonfeature',
            name='annotation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
