# Generated by Django 5.0 on 2024-03-15 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_alter_location_lines_alter_location_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='locations',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='apiapp.location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='lines',
            field=models.ManyToManyField(blank=True, to='apiapp.linestringlocation'),
        ),
        migrations.AlterField(
            model_name='location',
            name='points',
            field=models.ManyToManyField(blank=True, to='apiapp.pointlocation'),
        ),
        migrations.AlterField(
            model_name='location',
            name='polygons',
            field=models.ManyToManyField(blank=True, to='apiapp.polygonlocation'),
        ),
    ]
