# Generated by Django 5.0 on 2024-03-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_rename_locations_answer_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='interview_uuid',
            new_name='response_id',
        ),
    ]
