# Generated by Django 5.0 on 2024-07-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0008_rename_show_text_question_has_text_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linefeature',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.locationcollection'),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.locationcollection'),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.locationcollection'),
        ),
    ]
