# Generated by Django 5.0 on 2024-03-15 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0009_alter_answer_locations_alter_location_lines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.location'),
        ),
    ]
