# Generated by Django 5.0 on 2024-07-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_rename_submit_messsage_survey_submit_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='submit_message',
            field=models.TextField(blank=True, default='Thank you for your participation!', verbose_name='Message to be displayed after survey is submitted'),
        ),
    ]
