# Generated by Django 5.0 on 2024-03-20 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0011_alter_answer_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='location',
            name='points',
        ),
        migrations.RemoveField(
            model_name='location',
            name='polygons',
        ),
        migrations.AddField(
            model_name='location',
            name='lines',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.linestringlocation'),
        ),
        migrations.AddField(
            model_name='location',
            name='points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.pointlocation'),
        ),
        migrations.AddField(
            model_name='location',
            name='polygons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.polygonlocation'),
        ),
    ]
