# Generated by Django 5.0 on 2024-12-20 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_alter_survey_submit_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150, verbose_name='topic name')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiapp.question')),
            ],
        ),
    ]
