# Generated by Django 5.0 on 2024-03-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_remove_location_lines_remove_location_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='lines',
        ),
        migrations.RemoveField(
            model_name='location',
            name='polygons',
        ),
    ]
