# Generated by Django 5.0 on 2024-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0012_alter_response_respondent_alter_response_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapview',
            name='name',
            field=models.CharField(blank=True, default='Delft', max_length=150, verbose_name='Name of the MapView location'),
        ),
    ]
