# Generated by Django 5.0 on 2024-04-30 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0013_alter_mapview_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='location',
        ),
        migrations.AddField(
            model_name='answer',
            name='mapview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.mapview'),
        ),
    ]
