# Generated by Django 5.0 on 2024-03-27 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0013_remove_location_lines_remove_location_polygons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='points',
        ),
        migrations.AddField(
            model_name='polygonlocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.location'),
        ),
    ]
