# Generated by Django 5.0 on 2024-03-27 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_remove_location_points_polygonlocation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.location'),
        ),
    ]
