# Generated by Django 5.0 on 2024-12-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_alter_dashboardtopic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardtopic',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='topic name'),
        ),
    ]
