# Generated by Django 5.0 on 2024-04-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0014_remove_answer_location_answer_mapview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='map_view',
            new_name='mapview',
        ),
    ]
