# Generated by Django 5.0 on 2024-03-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0015_pointlocation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='question',
        ),
        migrations.RemoveField(
            model_name='pointlocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='polygonlocation',
            name='location',
        ),
    ]
