# Generated by Django 5.0 on 2024-12-27 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0015_alter_dashboardtopic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardtopic',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.dashboardtopic'),
        ),
    ]
