# Generated by Django 5.0 on 2024-05-01 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0015_rename_map_view_question_mapview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='mapview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiapp.mapview'),
        ),
        migrations.AlterField(
            model_name='linefeature',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apiapp.locationcollection'),
        ),
        migrations.AlterField(
            model_name='pointfeature',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apiapp.locationcollection'),
        ),
        migrations.AlterField(
            model_name='polygonfeature',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='apiapp.locationcollection'),
        ),
        migrations.AlterField(
            model_name='question',
            name='mapview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='apiapp.mapview'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
