# Generated by Django 5.0 on 2024-12-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0016_remove_dashboardtopic_question_question_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topic',
            new_name='topics',
        ),
    ]
