# Generated by Django 5.0 on 2024-03-27 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0016_remove_location_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='points',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.pointlocation'),
        ),
    ]
