# Generated by Django 5.0 on 2024-12-27 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0017_rename_topic_question_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topics',
        ),
        migrations.AddField(
            model_name='dashboardtopic',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.question'),
        ),
    ]
