# Generated by Django 5.0 on 2024-12-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0018_remove_question_topics_dashboardtopic_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardtopic',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, to='apiapp.dashboardtopic', verbose_name='Topics'),
        ),
    ]
