# Generated by Django 5.0 on 2024-03-27 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0018_remove_location_points_pointlocation_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointlocation',
            name='location',
        ),
    ]
