# Generated by Django 5.0 on 2024-03-27 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0019_remove_pointlocation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.question'),
        ),
    ]
