# Generated by Django 5.0 on 2024-12-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0020_alter_question_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(blank=True, to='apiapp.dashboardtopic', verbose_name='Topics'),
        ),
    ]
