# Generated by Django 5.0 on 2024-03-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0021_location_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('descripion', models.CharField(blank=True, max_length=300)),
                ('points', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.pointlocation')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.question')),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='locations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiapp.locationcollection'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
