# Generated by Django 5.2.3 on 2025-09-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)'), ('radio', 'radio'), ('select-multiple', 'Select Multiple'), ('integer', 'integer'), ('float', 'float'), ('date', 'date'), ('image-upload', 'image upload'), ('likert-scale', 'likert scale')], default='text', max_length=150, verbose_name='Type of question'),
        ),
    ]
