# Generated by Django 5.2.3 on 2025-09-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0003_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Question must be filled out'),
        ),
    ]
