# Generated by Django 5.2.3 on 2025-10-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0004_alter_question_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('long-text', 'long text'), ('short-text', 'short text'), ('single-choice', 'single choice'), ('multiple-choice', 'multiple choice'), ('number-int', 'number int'), ('number-float', 'number float'), ('date', 'date'), ('image-upload', 'image upload'), ('likert-scale', 'likert scale')], default='long-text', max_length=150, verbose_name='Type of question'),
        ),
    ]
