# Generated by Django 5.2.3 on 2025-08-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0006_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='likert_config',
            field=models.JSONField(blank=True, default=dict, help_text='JSON configuration for Likert scale labels and values', null=True, verbose_name='Likert Scale configuration'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'text (multiple line)'), ('short-text', 'short text (one line)'), ('radio', 'radio'), ('select', 'select'), ('select-multiple', 'Select Multiple'), ('integer', 'integer'), ('float', 'float'), ('date', 'date'), ('image-upload', 'Image Upload'), ('likert-scale', 'Likert Scale')], default='text', max_length=150, verbose_name='Type of question'),
        ),
    ]
