# Generated by Django 5.2.3 on 2025-10-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0006_alter_question_is_geospatial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_geospatial',
            field=models.BooleanField(default=False, verbose_name='Make Geospatial question'),
        ),
    ]
