# Generated by Django 5.2.3 on 2026-01-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0007_alter_question_is_geospatial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='shareable_link_created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Shareable Link Created At'),
        ),
        migrations.AddField(
            model_name='survey',
            name='shareable_link_enabled',
            field=models.BooleanField(default=False, help_text='Whether the shareable link is active', verbose_name='Shareable Link Enabled'),
        ),
        migrations.AddField(
            model_name='survey',
            name='shareable_link_expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional expiration date for the shareable link', null=True, verbose_name='Shareable Link Expires At'),
        ),
        migrations.AddField(
            model_name='survey',
            name='shareable_link_requires_auth',
            field=models.BooleanField(default=False, help_text='Whether users must be authenticated to access via shareable link', verbose_name='Shareable Link Requires Authentication'),
        ),
        migrations.AddField(
            model_name='survey',
            name='shareable_token',
            field=models.CharField(blank=True, db_index=True, help_text='Cryptographically secure token for shareable link access', max_length=64, null=True, unique=True, verbose_name='Shareable Link Token'),
        ),
    ]
