from .models import (
    Answer,
    Question,
    Survey,
    PointFeature,
    DashboardTopic,
    PolygonFeature,
    LineFeature,
    MapView,
    LocationCollection,
)
from .models import Response as ResponseModel
from .permissions import IsAuthenticatedAndSelfOrMakeReadOnly, IsAuthenticatedAndSelf, CanAccessSurvey
from rest_framework.decorators import api_view
from rest_framework.mixins import UpdateModelMixin
from rest_framework.response import Response
from rest_framework import viewsets, status
from rest_framework.decorators import action
from rest_framework.response import Response as rf_response
from django.middleware import csrf
from django.utils import timezone
from .serializers import (
    AnswerSerializer,
    LocationCollectionSerializer,
    PointFeatureSerializer,
    QuestionSerializer,
    SurveySerializer,
    ResponseSerializer,
    VoiceUserSerializer,
    MapViewSerializer,
    LineFeatureSerializer,
    PolygonFeatureSerializer,
    AnswerCSVSerializer,
    TopicSerializer,
)
from rest_framework.permissions import AllowAny, IsAuthenticated
from django.contrib.auth.models import User
from datetime import datetime
from django.shortcuts import get_object_or_404
from rest_framework.parsers import MultiPartParser, FormParser
import csv
from django.http import HttpResponse
from drf_spectacular.utils import extend_schema
from drf_spectacular.views import SpectacularAPIView


@extend_schema(
    summary="Get CSRF token",
    description="Retrieve a CSRF token for making authenticated requests.",
    operation_id="getCSRFToken",
)
@api_view(["GET"])
def get_csrf_token(request):
    token = csrf.get_token(request)
    return rf_response({"csrf_token": token})


# You need this new class to be able to change the name & description of the autogenerated voice_v3_schema_retrieve endpoint.
class VoiceSchemaView(SpectacularAPIView):
    @extend_schema(
        summary="API Schema",
        description="Retrieve the OpenAPI 3.0 schema for the Voice API",
        operation_id="getVoiceAPISchema",
    )
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class AnswerViewSet(viewsets.ModelViewSet):
    """
    Answer ViewSet used internally to query data from database.
    """

    # Figure out the permissions for the answers, do designers to to see them?
    # permission_classes = [IsAuthenticatedAndSelfOrMakeReadOnly]
    serializer_class = AnswerSerializer
    parser_classes = [MultiPartParser, FormParser]

    def get_queryset(self):
        """
        Returns a set of all Answer instances in the database, or
        filters the queryset based on the query parameters.

        Parameters:
            question (int): Question ID to be used for finding related Answers
            survey (int): Survey ID to be used for finding related Answers

        Returns:
            queryset:
        """

        queryset = Answer.objects.all()
        question_id = self.request.query_params.get("question", None)

        if question_id is not None:
            queryset = queryset.filter(question_id=question_id)
        survey_id = self.request.query_params.get("survey", None)

        if survey_id is not None and question_id is None:
            queryset = queryset.filter(question__survey_id=survey_id)
        return queryset

    @extend_schema(
        summary="Upload an image answer",
        description="Handle the upload of an image for an answer.",
    )
    @action(
        detail=False, methods=["post"], parser_classes=[MultiPartParser, FormParser]
    )
    def upload_image_answer(self, request):
        """Handle image upload for answers."""
        serializer = self.get_serializer(data=request.data)
        if serializer.is_valid():
            answer = serializer.save()
            return rf_response(
                AnswerSerializer(answer, context={"request": request}).data,
                status=status.HTTP_201_CREATED,
            )
        return rf_response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def create(self, request, *args, **kwargs):
        """Override create to handle both regular and image uploads."""
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        answer = serializer.save()

        # Return the created answer with full serialization
        response_serializer = AnswerSerializer(answer, context={"request": request})
        return rf_response(
            response_serializer.data,
            status=status.HTTP_201_CREATED,
            headers=self.get_success_headers(response_serializer.data),
        )

    @staticmethod
    def GetAnswerByResponse(response_id):
        """
        Get all answers by filtering based either on their related Response.

        Parameters:
            response_id (int): Response ID to be used for finding related Answers

        Return:
            queryset: containing all Answer instances with this response_id
        """
        queryset = Answer.objects.filter(response=response_id)
        return queryset

    @extend_schema(
        summary="Download answers as CSV",
        description="Download all answers as a CSV file for offline analysis or reporting.",
        operation_id="downloadAnswersCSV",
    )
    @action(detail=False, methods=["get"], url_path="csv")
    def download_csv(self, request, *args, **kwargs):
        queryset = Answer.objects.all()
        serializer = AnswerCSVSerializer(
            queryset, context={"request": request}, many=True
        )

        response = HttpResponse(content_type="text/csv")
        response["Content-Disposition"] = 'attachment; filename="answers.csv"'

        def flatten_dict(d, parent_key="", sep="."):
            items = []
            for k, v in d.items():
                new_key = f"{parent_key}{sep}{k}" if parent_key else k
                if isinstance(v, dict):
                    items.extend(flatten_dict(v, new_key, sep=sep).items())
                else:
                    items.append((new_key, v))
            return dict(items)

        flatten_data = [flatten_dict(answer) for answer in serializer.data]

        writer = csv.writer(response)
        headers = set()
        for item in flatten_data:
            headers.update(item.keys())
        writer.writerow(list(headers))

        for answer in flatten_data:
            _rows = []
            for field in headers:
                try:
                    _row = answer[field]
                    _rows.append(_row)
                except KeyError:
                    print("KeyError", field)
                    _row = ""
                    _rows.append(_row)
            writer.writerow(_rows)

            # writer.writerow([answer[field] for field in headers])

        return response


class QuestionViewSet(viewsets.ModelViewSet, UpdateModelMixin):
    """
    Question ViewSet used to query data from database.
    The `create` method is overwritten to accept one data object or an array of objects.
    """

    permission_classes = [IsAuthenticatedAndSelfOrMakeReadOnly]
    queryset = Question.objects.all()
    serializer_class = QuestionSerializer

    def create(self, request, *args, **kwargs):
        """
        Here we are overwriting the default create method from the Django REST framework to update or create Questions by list or by single instances
        """
        # Checks if the request data is a list, and if not it wraps it in a list
        data = request.data if isinstance(request.data, list) else [request.data]
        questions = []
        """
        Here we iterate over each item in the list and checks if it has an 'id' field. If it does, 
        it retrieves the existing Question object with that ID (if it exists). 
        If it doesn't have an 'id' field, it creates a new Question object.
        """

        for question_data in data:
            if "id" in question_data:
                question = Question.objects.filter(pk=question_data["id"]).first()
                if question is None:
                    continue
                serializer = self.get_serializer(
                    question,
                    data=question_data,
                    partial=True,
                    context={"request": request},
                )
            else:
                serializer = self.get_serializer(
                    data=question_data, context={"request": request}
                )
            serializer.is_valid(raise_exception=True)
            question = serializer.save()
            questions.append(question)

        update_fields = [
            "text",
            "explanation",
            "order",
            "required",
            "question_type",
            "choices",
            "survey",
            "is_geospatial",
            "has_text_input",
            "mapview",
            "topics",
        ]

        serializer = self.get_serializer(questions, many=True)
        headers = self.get_success_headers(serializer.data)
        return rf_response(
            serializer.data, status=status.HTTP_201_CREATED, headers=headers
        )

    def perform_create(self, serializer):
        update_fields = [
            "text",
            "explanation",
            "order",
            "required",
            "question_type",
            "choices",
            "survey",
            "is_geospatial",
            "has_text_input",
            "map_view",
        ]
        serializer.save(update_fields=update_fields)

    def perform_update(self, serializer):
        serializer.save(
            update_fields=[
                "text",
                "explanation",
                "order",
                "required",
                "question_type",
                "choices",
                "survey",
                "is_geospatial",
                "show_text",
                "map_view",
            ],
            update_conflicts={
                "text": "keep",
                "explanation": "keep",
                "order": "keep",
                "required": "keep",
                "question_type": "keep",
                "choices": "keep",
                "survey": "keep",
                "is_geospatial": "keep",
                "has_text_input": "keep",
                "map_view": "keep",
            },
        )

    @extend_schema(
        summary="Get ordered questions for survey",
        description="Retrieve all questions belonging to a specific survey, ordered by their sequence number (order field).",
        operation_id="getOrderedQuestions",
    )
    @action(detail=True, methods=["get"])
    def ordered_questions(self, request, pk=None):
        """
        Retrieve a list of questions for a given survey, ordered by the 'order' field.
        API url: `/api/questions/{survey_id}/ordered_questions`

        Parameters:
            request (Request): The request object used to make the API call.
            pk = survey_id (int): The primary key of the Survey instance to retrieve questions for.

        Returns:
            Response: A JSON response containing a list of serialized Question instances.
        """
        survey = get_object_or_404(Survey, pk=pk)
        questions = survey.question_set.all().order_by("order")
        serializer = self.get_serializer(questions, many=True)
        return rf_response(serializer.data)


class SurveyViewSet(viewsets.ModelViewSet):
    """
    Survey ViewSet used internally to query data from database.

    """

    permission_classes = [CanAccessSurvey]
    serializer_class = SurveySerializer

    def get_queryset(self):
        """
        Returns surveys based on user authentication:
        - Authenticated users: public surveys + their own surveys
        - Anonymous users: only public surveys
        - Private surveys (need_logged_user=True) only visible to designer
        """
        user = self.request.user
        now = timezone.now()
        
        # Base queryset: published and not expired
        base_queryset = Survey.objects.filter(
            is_published=True,
            expire_date__gte=now
        )
        
        if user.is_authenticated:
            # Authenticated users see:
            # 1. Public surveys (need_logged_user=False)
            # 2. Their own surveys (regardless of need_logged_user or publish status, but not expired)
            public_surveys = base_queryset.filter(need_logged_user=False)
            # Own surveys: include unpublished and private, but exclude expired
            own_surveys = Survey.objects.filter(
                designer=user,
                expire_date__gte=now
            )
            
            # Combine and remove duplicates
            queryset = (public_surveys | own_surveys).distinct().order_by("name")
        else:
            # Anonymous users only see public surveys
            queryset = base_queryset.filter(need_logged_user=False).order_by("name")
        
        return queryset

    def get_object(self):
        """
        Override to check permissions even if object is not in queryset.
        This ensures we return 403 (Forbidden) instead of 404 (Not Found)
        when user tries to access a survey they don't have permission to see.
        """
        # Get the object directly by pk, bypassing queryset filtering
        # This allows us to check permissions even if the object is filtered out
        lookup_url_kwarg = self.lookup_url_kwarg or self.lookup_field
        filter_kwargs = {self.lookup_field: self.kwargs[lookup_url_kwarg]}
        
        try:
            obj = Survey.objects.get(**filter_kwargs)
        except Survey.DoesNotExist:
            from rest_framework.exceptions import NotFound
            raise NotFound("Survey not found.")
        
        # Check object permissions (this will raise PermissionDenied if denied)
        self.check_object_permissions(self.request, obj)
        
        return obj

    @extend_schema(
        summary="Get my surveys",
        description="Retrieve all surveys created by the authenticated user, ordered alphabetically by name.",
        operation_id="getMySurveys",
    )
    @action(detail=False, methods=["GET"], url_path="my-surveys")
    def my_surveys(self, request, *args, **kwargs):
        """
        Get all surveys created by the authenticated user.
        Requires authentication.
        """
        user = self.request.user
        
        if not user.is_authenticated:
            return rf_response(
                {"detail": "Authentication credentials were not provided."},
                status=status.HTTP_401_UNAUTHORIZED
            )
        
        surveys_of_user = Survey.objects.filter(designer=user).order_by("name")
        survey_serializer = self.get_serializer(surveys_of_user, many=True)
        return rf_response(survey_serializer.data)

    @extend_schema(
        summary="Create a new survey",
        description="Create a new survey with the specified name and description. The authenticated user becomes the survey designer.",
        operation_id="createNewSurvey",
    )
    @action(detail=False, methods=["POST"], url_path="create-survey")
    def create_survey(self, request, *args, **kwargs):
        """
        Create a new survey. Requires authentication.
        The authenticated user becomes the survey designer.
        """
        user = self.request.user
        
        if not user.is_authenticated:
            return rf_response(
                {"detail": "Authentication credentials were not provided."},
                status=status.HTTP_401_UNAUTHORIZED
            )
        
        survey_name = self.request.data.get("name")
        survey_description = self.request.data.get("description", "")
        
        if not survey_name:
            return rf_response(
                {"detail": "Survey name is required."},
                status=status.HTTP_400_BAD_REQUEST
            )
        
        once_up_a_time = datetime.now()
        tz_aware_datetime = timezone.make_aware(once_up_a_time)

        survey = Survey(
            name=survey_name,
            description=survey_description,
            publish_date=tz_aware_datetime,
            expire_date=tz_aware_datetime,
            designer=user,
        )
        survey.save()

        survey_serializer = SurveySerializer(
            survey, context={"request": request}
        )
        return rf_response(survey_serializer.data, status=status.HTTP_201_CREATED)

    @extend_schema(
        summary="Get survey questions",
        description="Retrieve questions for a published survey, ordered by sequence.",
        operation_id="getSurveyQuestions",
    )
    @action(detail=True, methods=["GET"], url_path="questions")
    def get_questions_of_survey(self, request, pk=None):
        """
        Get questions for a survey.
        Access rules:
        - Published public surveys: anyone can access
        - Published private surveys: only designer can access
        - Unpublished surveys: only designer can access
        """
        try:
            survey = Survey.objects.get(id=pk)
        except Survey.DoesNotExist:
            return rf_response(
                {"detail": "Survey not found."},
                status=status.HTTP_404_NOT_FOUND
            )
        
        user = self.request.user
        
        # Check access permissions
        # If survey is not published, only designer can access
        if not survey.is_published:
            if not user.is_authenticated or survey.designer != user:
                return rf_response(
                    {"detail": "You do not have permission to access this survey."},
                    status=status.HTTP_403_FORBIDDEN
                )
        
        # If survey is private (need_logged_user=True), only designer can access
        elif survey.need_logged_user:
            if not user.is_authenticated or survey.designer != user:
                return rf_response(
                    {"detail": "This survey requires authentication and ownership."},
                    status=status.HTTP_403_FORBIDDEN
                )
        
        # Survey is published and public, or user has access
        questions = Question.objects.filter(survey_id=pk).order_by("order")
        question_serializer = QuestionSerializer(
            questions, many=True, context={"request": request}
        )
        return rf_response(question_serializer.data)

    # @action(detail=True, methods=['post'])
    # def CreateSurvey(response):
    #     """
    #     Create a survey
    #     """
    #     data = JSONParser().parse(response)
    #     survey_serializer = SurveySerializer(data=data, context={'request': response})
    #     if survey_serializer.is_valid():
    #         survey_serializer.save()
    #         return JsonResponse(survey_serializer.data, status=status.HTTP_201_CREATED)
    #     return JsonResponse(survey_serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    @staticmethod
    def GetSurveyByID(id):
        """
        Get a specific Survey based on its ID.

        Parameters:
            id (int): Survey ID to be used for finding this Survey.

        Return:
            queryset: containing the Survey instance with this id
        """
        queryset = Survey.objects.filter(id=id)
        return queryset

    @staticmethod
    def GetSurveyByDesigner(designer, unexpired_only=False):
        """
        Get a specific Survey based on its author.

        Parameters:
            designer (int): User ID to be used for finding related Surveys.
            unexpired_only (bool):  True - only unexpired surveys (by current date and time) will be returned
                                    False - all surveys will be returned
                                    default = True

        Return:
            queryset: containing the Survey instances related to this user
        """
        if unexpired_only:
            now = datetime.now()
            queryset = Survey.objects.filter(designer=designer, expire_date__gte=now)
        else:
            queryset = Survey.objects.filter(designer=designer)
        return queryset

    @staticmethod
    def GetSurveyByAvailable():
        """
        Get a all Surveys that are still available (current date is not past expiration date).

        Return:
            queryset: containing the Survey instances that have not expired yet
        """

        now = datetime.now()
        queryset = Survey.objects.filter(expire_date__gte=now)
        return queryset


class ResponseViewSet(viewsets.ModelViewSet):
    """
    Response ViewSet used internally to query data from database.
    """

    serializer_class = ResponseSerializer
    """
    POST method is used to create a new response
    Example of a POST request body (JSON):
    {
    "survey": "http://localhost:8000/api/v2/surveys/1/",
    "respondent": "http://localhost:8000/api/v2/users/1/"
    }

    Returns a JSON response with the created response:

    {
    "response_id": "uuid",
    "url": "http://localhost:8000/api/v2/responses/uuid/",
    "created": "2024-04-12T14:31:02.476427Z",
    "updated": "2024-04-12T14:31:02.476456Z",
    "survey": "http://localhost:8000/api/v2/surveys/1/",
    "respondent": "http://localhost:8000/api/v2/users/1/"
    }

    """

    def get_queryset(response):
        """
        Returns a set of all Response instances in the database.

        Return:
            queryset: containing all Response instances
        """

        queryset = ResponseModel.objects.all().order_by("created")
        return queryset

    @extend_schema(
        summary="Submit survey response",
        description="Submit answers for a survey response. This endpoint processes multiple answers associated with a response ID.",
        operation_id="submitSurveyResponse",
    )
    @action(detail=False, methods=["POST"], url_path="submit-response")
    def submit_response(self, request, *args, **kwargs):
        print("Submitting response...")

        user = self.request.user
        answers = self.request.data["answers"]
        responseId = self.request.data["responseId"]
        if type(user) is User:
            print("User:")
            print(str(User))
        else:
            print("User was anonymous")
        time = datetime.now()

        for answer in answers:
            text = answer["_text"]
            resp = ResponseModel.objects.get(pk=int(responseId))
            quest = Question.objects.get(pk=1)
            storedAnswer = Answer(
                response=resp, question=quest, created=time, updated=time, body=text
            )

            print(str(answer))

            return rf_response(None)

    # @action(detail=True, methods=['POST'], url_path='create-response')
    def create(self, request, pk=None):
        survey_id = request.data.get("survey")
        if survey_id is None:
            return rf_response(
                {"message": "a survey is required"}, status=status.HTTP_400_BAD_REQUEST
            )

        request_serializer = ResponseSerializer(
            data=request.data, context={"request": request}
        )
        request_serializer.is_valid(raise_exception=True)
        response = request_serializer.save()

        # deserialize the nested response objects by
        # creating a new ResponseSerializer instance
        response_serializer = ResponseSerializer(response, context={"request": request})

        return rf_response(
            response_serializer.data,
            status=status.HTTP_201_CREATED,
            headers=self.get_success_headers(response_serializer.data),
        )

    @staticmethod
    def GetResponseByID(id):
        """
        Get a specific Response based on its ID.

        Parameters:
            id (int): Response ID to be used for finding this Response.

        Return:
            queryset: containing the Response instance with this id
        """
        queryset = ResponseModel.objects.filter(id=id)
        return queryset

    @staticmethod
    def GetResponseBySurvey(survey_id):
        """
        Get a specific Response based on its survey.

        Parameters:
            survey_id (int): Survey ID to be used for finding related Responses.

        Return:
            queryset: containing the Response instances related to this Survey
        """

        queryset = ResponseModel.objects.filter(response=survey_id)
        return queryset

    @staticmethod
    def GetResponseByRespondent(respondent):
        """
        Get a specific Response based on its respondent.

        Parameters:
            respondent (int): User ID to be used for finding related Responses.

        Return:
            queryset: containing the Response instances related to this respondent/ user
        """

        queryset = ResponseModel.objects.filter(user=respondent)
        return queryset


class UserViewSet(viewsets.ModelViewSet):
    """
    User ViewSet used internally to query data from database for all users.
    """

    permission_classes = [IsAuthenticatedAndSelf]
    serializer_class = VoiceUserSerializer

    def get_queryset(response):
        """
        Returns a set of all User instances in the database.

        Return:
            queryset: containing all User instances
        """

        queryset = User.objects.all().order_by("username")
        return queryset


class LocationViewSet(viewsets.ModelViewSet):
    """
    Location ViewSet used internally to query data from database for all users.
    """

    serializer_class = LocationCollectionSerializer
    queryset = LocationCollection.objects.all()

    @extend_schema(
        summary="Get location features",
        description="Retrieve all geographic features (points, lines, and polygons) associated with a specific location collection.",
        operation_id="getLocationFeatures",
    )
    @action(detail=True, methods=["get"])
    def features(self, request, *args, **kwargs):
        points = PointFeature.objects.filter(location_id=self.kwargs["pk"])
        serializer = PointFeatureSerializer(
            points, many=True, context={"request": request}
        )

        polygons = PolygonFeature.objects.filter(location_id=self.kwargs["pk"])
        polygon_serializer = PolygonFeatureSerializer(
            polygons, many=True, context={"request": request}
        )

        lines = LineFeature.objects.filter(location_id=self.kwargs["pk"])
        line_serializer = LineFeatureSerializer(
            lines, many=True, context={"request": request}
        )

        serializer_data = serializer.data
        serializer_data.extend(line_serializer.data)
        serializer_data.extend(polygon_serializer.data)
        return Response(serializer_data)


class PointFeatureViewSet(viewsets.ModelViewSet):
    """
    PointLocation ViewSet used internally to query data from database for all users.
    """

    serializer_class = PointFeatureSerializer

    def get_queryset(response):
        """
        Returns a set of all PointFeature instances in the database.

        Return:
            queryset: containing all PointFeature instances
        """

        queryset = PointFeature.objects.all()
        return queryset


class PolygonFeatureViewSet(viewsets.ModelViewSet):
    """
    PolygonFeature ViewSet used internally to query data from database for all users.
    """

    serializer_class = PolygonFeatureSerializer

    def get_queryset(response):
        """
        Returns a set of all PolygonFeature instances in the database.

        Return:
            queryset: containing all PolygonFeature instances
        """

        queryset = PolygonFeature.objects.all()
        return queryset

    @staticmethod
    def GetLocationsByQuestion(question):
        """
        Get a list of PointFeatures associated to this question.

        Parameters:
            question (int): Question ID to be used for finding related PointFeatures.

        Return:
            queryset: containing the PointFeature instances related to this Question
        """

        queryset = PointFeature.objects.filter(question=question)
        return queryset

    @staticmethod
    def GetLocationsByAnswer(answer):
        """
        Get a list of PolygonFeatures associated to this answer.

        Parameters:
            answer (int): Answer ID to be used for finding related PolygonFeatures.

        Return:
            queryset: containing the PolygonFeature instances related to this Answer
        """

        queryset = PolygonFeature.objects.filter(answer=answer)
        return queryset


class LineFeatureViewSet(viewsets.ModelViewSet):
    """
    LineStringLocation ViewSet used internally to query data from database for all users.
    """

    serializer_class = LineFeatureSerializer

    def get_queryset(response):
        """
        Returns a set of all LineStringLocation instances in the database.

        Return:
            queryset: containing all LineStringLocation instances
        """

        queryset = LineFeature.objects.all()
        return queryset

    @staticmethod
    def GetLocationsByQuestion(question):
        """
        Get a list of LineStringLocations associated to this question.

        Parameters:
            question (int): Question ID to be used for finding related LineStringLocations.

        Return:
            queryset: containing the LineStringLocation instances related to this Question
        """

        queryset = LineFeature.objects.filter(question=question)
        return queryset

    @staticmethod
    def GetLocationsByAnswer(answer):
        """
        Get a list of LineStringLocations associated to this answer.

        Parameters:
            answer (int): Answer ID to be used for finding related LineStringLocations.

        Return:
            queryset: containing the LineStringLocation instances related to this Answer
        """

        queryset = LineFeature.objects.filter(answer=answer)
        return queryset


class MapViewViewSet(viewsets.ModelViewSet):
    """
    Question ViewSet used internally to query data from database.

    """

    serializer_class = MapViewSerializer

    def get_queryset(response):
        """
        Returns a set of all MapView instances in the database.

        Return:
            queryset: containing all MapView instances
        """

        queryset = MapView.objects.all().order_by("id")
        return queryset

    @extend_schema(exclude=True)  # Exclude this action from the API documentation
    @action(detail=False, methods=["get"])
    def id_names(self, request):
        mapviews = MapView.objects.values("id", "name")
        return Response(mapviews)


class TopicViewSet(viewsets.ModelViewSet):
    """
    A ViewSet that returns the topics associated to a question
    """

    serializer_class = TopicSerializer

    def get_queryset(self):
        queryset = DashboardTopic.objects.all()
        return queryset


import monkey_patch

# Manually patch all ViewSets
monkey_patch.patch_viewset_class(AnswerViewSet)
monkey_patch.patch_viewset_class(QuestionViewSet)
monkey_patch.patch_viewset_class(SurveyViewSet)
monkey_patch.patch_viewset_class(ResponseViewSet)
monkey_patch.patch_viewset_class(UserViewSet)
monkey_patch.patch_viewset_class(LocationViewSet)
monkey_patch.patch_viewset_class(PointFeatureViewSet)
monkey_patch.patch_viewset_class(PolygonFeatureViewSet)
monkey_patch.patch_viewset_class(LineFeatureViewSet)
monkey_patch.patch_viewset_class(MapViewViewSet)
monkey_patch.patch_viewset_class(TopicViewSet)
