export const LONG_TEXT = "long-text",
    SHORT_TEXT = "short-text",
    SINGLE_CHOICE = "single-choice",
    MULTIPLE_CHOICE = "multiple-choice",
    INTEGER = "number-int",
    FLOAT = "number-float",
    DATE = "date",
    IMAGE_UPLOAD = "image-upload",
    LIKERT_SCALE = "likert-scale"